[package]
name = "skip-swap-valence-strategist"
version = "0.2.0"
authors = ["Timewave Labs"]
edition = "2021"
description = "Off-chain component for the Skip Swap Valence library that finds optimal routes via the Skip API"
license = "Apache-2.0"
repository = "https://github.com/timewave-computer/valence-protocol"

[dependencies]
cosmwasm-std = { version = "2.1.3" }
schemars = "0.8.16"
serde = { version = "1.0.207", default-features = false, features = ["derive"] }
thiserror = "1.0.63"
serde_json = "1.0.125"
tokio = { version = "1.29", features = ["full"], optional = true }
reqwest = { version = "0.11", features = ["json"], optional = true }
toml = "0.8"

[features]
default = ["runtime"]
runtime = ["tokio", "reqwest"]

[dev-dependencies]
tokio = { version = "1.29", features = ["full", "macros", "test-util"] }
mockall = "0.11" 