[package]
name = "skip-swap-valence-strategist"
version = "0.2.0"
authors = ["Timewave Labs"]
edition = "2021"
description = "Off-chain component for the Skip Swap Valence library that finds optimal routes via the Skip API"
license = "Apache-2.0"
repository = "https://github.com/timewave-computer/valence-protocol"

[dependencies]
cosmwasm-std = { version = "2.1.3" }
cosmwasm-schema = "1.2.1"
schemars = "0.8.16"
serde = { version = "1.0.207", default-features = false, features = ["derive"] }
thiserror = "1.0.63"
serde_json = "1.0.125"
tokio = { version = "1.29", features = ["full"], optional = true }
reqwest = { version = "0.11", features = ["json"], optional = true }
toml = "0.8"
async-trait = "0.1"
base64 = "0.21.7"
bip39 = { version = "2.0.0", optional = true }
k256 = { version = "0.13.1", features = ["ecdsa"], optional = true }
ripemd = { version = "0.1.3", optional = true }
sha2 = { version = "0.10.8", optional = true }
bech32 = { version = "0.9.1", optional = true }
hex = { version = "0.4.3", optional = true }
secp256k1 = { version = "0.27.0", features = ["rand"], optional = true }
rand = { version = "0.8.5", optional = true }
log = "0.4.17"
aes = { version = "0.8.3", optional = true }
ctr = { version = "0.9.2", optional = true }
hmac = { version = "0.12.1", optional = true }
pbkdf2 = { version = "0.12.2", optional = true }
scrypt = { version = "0.11.0", optional = true }
typenum = { version = "1.17.0", optional = true }

[features]
default = ["runtime"]
runtime = [
    "tokio", "reqwest", "bip39", "k256", "ripemd", "sha2", "bech32", "hex", "secp256k1", "rand",
    "aes", "ctr", "hmac", "pbkdf2", "scrypt", "typenum"
]

[dev-dependencies]
tokio = { version = "1.29", features = ["full", "macros", "test-util"] }
mockall = "0.11"
tempfile = "3.10.0"
rstest = "0.17.0" 