[package]
name       = "build_program"
edition    = { workspace = true }
license    = { workspace = true }
version    = { workspace = true }
repository = { workspace = true }

[dependencies]
serde_json                  = { workspace = true }
valence-program-manager     = { workspace = true }
valence-splitter-library    = { workspace = true }
valence-authorization-utils = { workspace = true }
valence-library-utils       = { workspace = true }
clap                        = { workspace = true }
