[package]
name = "account-factory-e2e"
version = "0.1.0"
edition = "2021"

[workspace]

[[bin]]
name = "account_factory"
path = "src/main.rs"

[dependencies]
# Core dependencies
cosmwasm-schema = "1.5.7"
cosmwasm-std = "1.5.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
anyhow = "1.0"
env_logger = "0.10"

# Crypto and utilities
sha2 = "0.10"
hex = "0.4"
reqwest = { version = "0.11", features = ["json"] }

# Account factory types
valence-account-factory = { path = "../../../contracts/accounts/account_factory" }

# Time utilities
chrono = { version = "0.4", features = ["serde"] }

# For working with domain clients (if needed)
# Note: Using minimal dependencies to avoid conflicts
futures = "0.3" 