[package]
name = "skip-swap-valence"
version = "0.1.0"
authors = ["Timewave <engineering@timewave.com>"]
edition = "2021"
description = "Valence Library for Skip Swap - facilitates token swaps via Skip Protocol for the Valence Protocol"
license = "Apache-2.0"

[workspace]

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all instantiate/execute/query exports
library = []

[dependencies]
cosmwasm-std = { version = "1.5.0", features = ["staking"] }
schemars = "0.8.16"
serde = { version = "1.0.188", default-features = false, features = ["derive"] }
serde-json-wasm = "1.0.0"
thiserror = "1.0.49"
cw-storage-plus = "1.2.0"

[dev-dependencies]
cw-multi-test = "0.17.0"
cosmwasm-schema = "1.5.0" 