[package]
name = "skip-swap-valence"
version = "0.2.0"
authors = ["Timewave Labs"]
edition = "2021"
description = "Valence Library for Skip Swap - facilitates token swaps via Skip Protocol for the Valence Protocol"
license = "Apache-2.0"
repository = "https://github.com/timewave-computer/valence-protocol"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# use library feature to disable all instantiate/execute/query exports
library = []

[dependencies]
cosmwasm-std = { version = "2.1.3" }
schemars = "0.8.16"
serde = { version = "1.0.207", default-features = false, features = ["derive"] }
serde_json = "1.0.125"
thiserror = "1.0.63"
cw-storage-plus = "2.0.0"
cw-utils = "2.0.0"
cw-ownable = "2.0.0"
valence-library-base = { path = "../../../../packages/library-base" }
valence-library-utils = { path = "../../../../packages/library-utils" }
valence-authorization-utils = { path = "../../../../packages/authorization-utils" }

[dev-dependencies]
cw-multi-test = "2.1.1"
cosmwasm-schema = "2.1.3" 