[formatting]
align_entries         = true
align_comments        = true
array_auto_expand     = true
array_auto_collapse   = true
compact_arrays        = false
compact_inline_tables = false
column_width          = 120
indent_string         = "    "
reorder_keys          = false
