[package]
name = "cosmwasm-account-factory-circuit"
version = "0.1.0"
edition = "2021"
description = "CosmWasm Account Factory ZK Circuit"
license = "Apache-2.0"
repository = "https://github.com/timewave-computer/valence-protocol"
authors = ["Timewave Computer <info@timewave.computer>"]

[workspace]

[dependencies]
# Cryptographic dependencies
sha2 = "0.10"
hex = "0.4"

# Serialization
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"

# ZK circuit dependencies
valence-coprocessor = { git = "https://github.com/timewave-computer/valence-coprocessor.git", tag = "v0.1.11", default-features = false }

[features]
default = [] 