[package]
name = "valence-chain-client-utils"
edition = { workspace = true }
license = { workspace = true }
version = { workspace = true }
repository = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# generic imports
tokio = "1.43.0"
async-trait = "0.1.77"
serde = { workspace = true }
serde_json = { workspace = true }

# cosmos-specific imports
bip32 = { version = "0.5", features = ["bip39"] }
cosmrs = { version = "0.21.1", features = ["cosmwasm", "rpc", "grpc"] }
cosmos-sdk-proto = { version = "0.26.1", features = ["grpc-transport", "grpc"] }
tonic = { version = "0.12.3", features = ["transport"] }
valence-processor-utils = { workspace = true }
hex = "0.4.3"
neutron-std = "5.1.2"
ibc = "0.57.0"

# evm-specific imports
alloy_signer_local = { package = "alloy-signer-local", version = "0.9.2", features = [
    "mnemonic",
    "keystore",
] }
alloy_primitives_encoder = { package = "alloy-primitives", version = "0.7.7" }
alloy_sol_types_encoder = { package = "alloy-sol-types", version = "0.7.7" }
alloy = { version = "0.9.2", features = [
    "eips",
    "full",
    "hyper",
    "json-rpc",
    "node-bindings",
    "rpc-client",
    "rpc-types-debug",
    "rpc-types-trace",
    "signer-keystore",
    "signer-mnemonic",
    "signers",
] }

[dev-dependencies]
valence-e2e = { workspace = true }
