[package]
name = "cosmwasm-account-factory-controller"
version = "0.1.0"
edition = "2021"
description = "CosmWasm Account Factory ZK Controller"

[workspace]

[dependencies]
# Cryptographic dependencies
sha2 = "0.10"
hex = "0.4"

# JSON handling
serde_json = "1.0"

# Serialization
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"

# Error handling
anyhow = "1.0" 