[contracts]

[contracts.code_ids.neutron]
authorization = 7217
processor     = 7218
base_account  = 7219
forwarder     = 7222

polytone_proxy   = 1
splitter         = 6049
reverse_splitter = 3

[contracts.code_ids.cosmos-hub]
polytone_proxy   = 1
processor        = 4
base_account     = 5987
authorization    = 5
splitter         = 6049
reverse_splitter = 3
