# Noble side configuration
[noble]
grpc_url    = "http://0.0.0.0"
grpc_port   = "37175"
chain_id    = "noble-1"
mnemonic    = "decorate bright ozone fork gallery riot bus exhaust worth way bone indoor calm squirrel merry zero scheme cotton until shop any excess stage laundry"

# Neutron side configuration
[neutron]
grpc_url    = "http://0.0.0.0"
grpc_port   = "37745"
chain_id    = "neutron-1"
mnemonic    = "decorate bright ozone fork gallery riot bus exhaust worth way bone indoor calm squirrel merry zero scheme cotton until shop any excess stage laundry"
target_pool = "neutron13nrd2qag9dww078z9a2way4kvzpr0k5dkv54e2xfmp2e2decfmjqh6xmhg"

[neutron.denoms]
lp_token = "factory/neutron13nrd2qag9dww078z9a2way4kvzpr0k5dkv54e2xfmp2e2decfmjqh6xmhg/astroport/share"
usdc     = "ibc/8E27BA2D5493AF5636760E354E46004562C46AB7EC0CC4C1CA14E9E20E2545B5"
ntrn     = "untrn"

[neutron.accounts]
deposit     = "neutron1ah5xxylq7rfnrldn0rtvlm77gpfk3jhlq9jq40z573u6dx0awnvqze5aqn"
position    = "neutron1xxr6slevyf6ka8ksv332a4s209k903c8tn2hmnku6xlkvl32skdq8drrhy"
withdraw    = "neutron1gr5lc8wsngv66gnwt6j0qnvsf40e79cknkej5pq7g9na64xmd5esjpetxp"
liquidation = "neutron12pyfu93u2dv0qxkw74swzv59lw58nq68cp0p2ujq5f08flrwkkgqgkxdpz"

[neutron.accounts.noble_inbound_ica]
library_account = "neutron1hyja4uyjktpeh0fxzuw2fmjudr85rk2qu98fa6nuh6d4qru9l0ssh3kgnu"
remote_addr     = "noble1kzj0ska27ty2d48zc9ee5d0qxnun8eykyqkj3dzdxzaag9ty8awqtkt72q"

[neutron.accounts.noble_outbound_ica]
library_account = "neutron1m74wv3xew5dsy2thf3jp0xadg8pdrk4h8ym70z0ehfwxl8a547asj05a7h"
remote_addr     = "noble1gt7n3d82npcgwfr32s07z32av6ewd35uysknuv50af0c42f6lq8ssxs7es"

[neutron.libraries]
neutron_ibc_transfer    = "neutron1vnfn0e4vnn58ydpm05wqcc9zp8t5ztwd5rw5f895lykqaezmuccqtv6wly"
noble_inbound_transfer  = "neutron1p4lqunauqgstt6ydszx59y3pg2tkaxlnujl9m5ldz7nqcrn6tjzq2xu93l"
noble_cctp_transfer     = "neutron1sgffmlhsa49xu7nk8nakmhzm8dtngslh05x3238z4jm79s5346ssgqtmpw"
astroport_lper          = "neutron1s66zhks8v3fm24974crzxufh7w6ktt69jq8e3zt8q7cyvr52vlqqymz0y4"
astroport_lwer          = "neutron1lqgdq9u8zhcvwwwz3xjswactrtq6qzptmlzlh6xspl34dxq32uhq44hq5v"
liquidation_forwarder   = "neutron1wqchrjh07e3kxaee59yrpzckwr94j03zchmdslypvkv6ps0684mshs9fws"
authorizations          = "neutron1el56sdn8ae9nmx2g4jp54gv2upww5z6l5ngttd27k4f2ttzrm3zq6zcznc"
processor               = "neutron1cyd63pk2wuvjkqmhlvp9884z4h89rqtn8w8xgz9m28hjd2kzj2cqt9gc49"

# Ethereum side configuration
[ethereum]
rpc_url = "http://localhost:8545"
mnemonic = "test test test test test test test test test test test junk"

[ethereum.denoms]
usdc_erc20 = "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9"

[ethereum.accounts]
deposit     = "0x5fbdb2315678afecb367f032d93f642f64180aa3"
withdraw    = "0xe7f1725e7734ce288f8367e1bb143e90bb3f0512"

[ethereum.libraries]
valence_vault   = "0x9a676e781a523b5d0c0e43731313a708cb607508"
cctp_forwarder  = "0x610178da211fef7d417bc0e6fed39f05609ad788"
lite_processor  = "0xa51c1fc2f0d1a1b8494ed1fe312d7c3a78ed91c0"
