[noble_cfg]
grpc_url = "http://0.0.0.0"
grpc_port = "41919"
chain_id = "localnoble-1"
mnemonic = "decorate bright ozone fork gallery riot bus exhaust worth way bone indoor calm squirrel merry zero scheme cotton until shop any excess stage laundry"

[neutron_cfg]
grpc_url = "http://0.0.0.0"
grpc_port = "39343"
chain_id = "localneutron-1"
mnemonic = "decorate bright ozone fork gallery riot bus exhaust worth way bone indoor calm squirrel merry zero scheme cotton until shop any excess stage laundry"
target_pool = "neutron19mq00qktg88afvt95yflknd79zhwxulagqsv0m4tanqejccyw4kq447wsm"

[neutron_cfg.denoms]
lp_token = "factory/neutron19mq00qktg88afvt95yflknd79zhwxulagqsv0m4tanqejccyw4kq447wsm/astroport/share"
usdc = "ibc/65D0BEC6DAD96C7F5043D1E54E54B6BB5D5B3AEC3FF6CEBB75B9E059F3580EA3"
ntrn = "untrn"

[neutron_cfg.accounts]
deposit = "neutron1fd0g9uxkzh8564pf4l5a2rpwknvwptrxc9j5ktfg48nfd08jl5lqllwztg"
position = "neutron1t0aeaxhvmt9cymvr4kjmu63jm529dq6yp3t33v83fgmvf3jyefaq2n6cz4"
withdraw = "neutron1lkj8xqh6vys08sp269zvreqf2pn9ccvs4dvecdy7t288xv8zzt8qkh2xxm"
liquidation = "neutron1cskeg5jt0yr6adnwl6ewl3l85l2hhnx4y8m87v0te90ymryhaecq7nyagp"

[neutron_cfg.accounts.noble_inbound_ica]
library_account = "neutron1te7hf89xclrprk4epunuyx38hmvjakhgszyvy3glk5fgeekl9rts6wcylj"
remote_addr = "noble1rql3ffeehvf0z46rzj449pnyu92p7vhgjvx9jqazfn3hgr6j4u5qszpyc0"

[neutron_cfg.accounts.noble_outbound_ica]
library_account = "neutron14ra3dhree28fcp2eryznq6mllpuf2u0daw3ay0yfukxxq9d5ynvsmyy553"
remote_addr = "noble1hxmy85erk574uetek4ukywmat2e9qwz5f3949nlpyajnwjl8p84q66e0c3"

[neutron_cfg.libraries]
neutron_ibc_transfer = "neutron1wzgusk6m6te25an7g93pjkekut5zcr98z8tl27qmsxxndry8hxcq7w3y65"
noble_inbound_transfer = "neutron14x5xnwzlus9dty9gzedz9cp0xk7dkn7ueanfclkz5eaqxxcld54skv969g"
noble_cctp_transfer = "neutron14y3e7na0xvdg7q6wt9qxxsmzzf8chfh03jj2wg3hkcwssdnwmpvsu786me"
astroport_lper = "neutron1xm27l3tp94atree0w3yznl3jcfjw4s7ne6sww9x0p358x2zrck8s7jt760"
astroport_lwer = "neutron144pls39n9hfwfsr0q4sdjz3wv63ee36qea4muk93782rc9mwn99ssxdvx0"
liquidation_forwarder = "neutron1g8f5td9wg22nnjcucqzfersygwmmj93cag53z3k7p5qez9um237s8eas2l"
authorizations = "neutron15ac4el6gq6r00tnp07u5gw7m42grxukyjd64jv3f6285pgsnvdmsuttwxl"
processor = "neutron1rhq7ld3zr37hjs5cgt0jhqkuv7p6g8ghqc2ku3drss3tm73dehds69mrjv"

[ethereum_cfg]
rpc_url = "http://localhost:8545"
mnemonic = "test test test test test test test test test test test junk"

[ethereum_cfg.denoms]
usdc_erc20 = "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9"

[ethereum_cfg.accounts]
deposit = "0x5FbDB2315678afecb367f032d93F642f64180aa3"
withdraw = "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512"

[ethereum_cfg.libraries]
valence_vault = "0x9A676e781A523b5d0C0e43731313A708CB607508"
cctp_forwarder = "0x610178dA211FEF7D417bC0e6FeD39F05609AD788"
lite_processor = "0xA51c1fc2f0D1a1b8494Ed1FE312d7C3a78Ed91C0"
