[noble]
grpc_url = "http://0.0.0.0"
grpc_port = "37175"
chain_id = "localnoble-1"
mnemonic = "decorate bright ozone fork gallery riot bus exhaust worth way bone indoor calm squirrel merry zero scheme cotton until shop any excess stage laundry"

[neutron]
grpc_url = "http://0.0.0.0"
grpc_port = "37745"
chain_id = "localneutron-1"
mnemonic = "decorate bright ozone fork gallery riot bus exhaust worth way bone indoor calm squirrel merry zero scheme cotton until shop any excess stage laundry"
target_pool = "neutron1g9wzqz5t428l4cfg8vz7et3ganuz5r0yggvm87y5sgvhc4jhpcxsr6ja6z"

[neutron.denoms]
lp_token = "factory/neutron1g9wzqz5t428l4cfg8vz7et3ganuz5r0yggvm87y5sgvhc4jhpcxsr6ja6z/astroport/share"
usdc = "ibc/8E27BA2D5493AF5636760E354E46004562C46AB7EC0CC4C1CA14E9E20E2545B5"
ntrn = "untrn"

[neutron.accounts]
deposit = "neutron182ecww6pu5qpjyhssph823gz35ha4mkd0998dnw343g8llky6wtsgul876"
position = "neutron10jexrene0s855vgsw9nn4tp39hsgans0reh8f7j7luu2rxv8k3csc5dm0p"
withdraw = "neutron18f8krme834mfx5fxwa48lkmsv8uv84ye6yv9usgdckd380c8pljsy6k50d"
liquidation = "neutron1hn07aul4r3j4lm02m7xv5c4m9dvy9kxnm24y3lk4csny6q3xnc8q5h6vew"

[neutron.accounts.noble_inbound_ica]
library_account = "neutron1g3n9k9rt44a0zwzr6hvvkgav0uflw4e60e6gvufarv5euk3suagsfp6ukq"
remote_addr = "noble19s4w9rsh9f78cgxnk8nxp643ysm9t5swcz3raeafnvtng92c5h2q9wyka5"

[neutron.accounts.noble_outbound_ica]
library_account = "neutron10v9hgmt4yzj2ljxgz7kf3rn62ussqup7rxudq5w43qr62hr473lqthcg8j"
remote_addr = "noble1smghfaelx0wm2600pm8stase6xpt95f52s2ew8nflch4fytvxnqsuqmy06"

[neutron.libraries]
neutron_ibc_transfer = "neutron1a2vmmcft3zarvdc724fazfxxrlttlaztycj50hxhdd8zf7qsfl6s9q5u60"
noble_inbound_transfer = "neutron1s3xvpy3crq5d4zq5j3dq9tvjrcqnrs6p522vgp2l9ka0eezw6hqqkjychj"
noble_cctp_transfer = "neutron1tc533twqt7286vy9ng9hqn2qaw9hnngrdanf584waer28gs335qqazrk6u"
astroport_lper = "neutron14uyqcvw4hyg4x30vr7k43pcjxsnvtuh2422y47tj2pm70u0xer8sd532hx"
astroport_lwer = "neutron1cramkf272khfc7sdzpnxytkh0hpym4vygdca7tveyp3qpur9plhqhlx7ln"
liquidation_forwarder = "neutron159rf6yllegj6a278y4we2kjy2x695uvsx5ca2axg4sfmsr9f5rqs4zl0v8"
authorizations = "neutron1wz9q06usjkehujag3yawlptu73gjhlskcl9lk2anp85hxslxyarsje807r"
processor = "neutron1tddsuf25rrjgl9ty9lazhxe38q66uva7eqak3qz2c8e4yk0gj0yqjc02tz"

[ethereum]
rpc_url = "http://localhost:8545"
mnemonic = "test test test test test test test test test test test junk"

[ethereum.denoms]
usdc_erc20 = "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9"

[ethereum.accounts]
deposit = "0x5FbDB2315678afecb367f032d93F642f64180aa3"
withdraw = "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512"

[ethereum.libraries]
valence_vault = "0x9A676e781A523b5d0C0e43731313A708CB607508"
cctp_forwarder = "0x610178dA211FEF7D417bC0e6FeD39F05609AD788"
lite_processor = "0xA51c1fc2f0D1a1b8494Ed1FE312d7C3a78Ed91C0"
