[noble]
grpc_url = "http://0.0.0.0"
grpc_port = "51340"
chain_id = "localnoble-1"
mnemonic = "decorate bright ozone fork gallery riot bus exhaust worth way bone indoor calm squirrel merry zero scheme cotton until shop any excess stage laundry"

[neutron]
grpc_url = "http://0.0.0.0"
grpc_port = "51360"
chain_id = "localneutron-1"
mnemonic = "decorate bright ozone fork gallery riot bus exhaust worth way bone indoor calm squirrel merry zero scheme cotton until shop any excess stage laundry"
target_pool = "neutron1a4vyfxj8qa9jrlz5cutgpj2s2sgsru863fnvsxsvg667m906l7kqxnvhg5"

[neutron.denoms]
lp_token = "factory/neutron1a4vyfxj8qa9jrlz5cutgpj2s2sgsru863fnvsxsvg667m906l7kqxnvhg5/astroport/share"
usdc = "ibc/F082B65C88E4B6D5EF1DB243CDA1D331D002759E938A0F5CD3FFDC5D53B3E349"
ntrn = "untrn"

[neutron.accounts]
deposit = "neutron1qpqqz06uk7yswe63z7wh0w4w8sw92rg2rrqpmuqp4hakm07ae0wql0ueyt"
position = "neutron1c5uu3fqtetqv4ru0lq8s4yevj8ryhudkz0tyqgd7pu54ydks293srkgmyv"
withdraw = "neutron184kanjdfcphg99qyp6l3pw2jqqsue960qkqknz98ydzgyu50fdjqlxj48w"
liquidation = "neutron1vfttvxh3ga4vvalqgmt6jmzfc7uk4ydl260pfupxrr2r2l99pxvsufx9gk"

[neutron.accounts.noble_inbound_ica]
library_account = "neutron1jhg90hj2y2s9jah0hrmjt25mqgmw72c8jstm2fqrlpcph2aw5dhq4zre22"
remote_addr = "noble1c973pmtrvtpa7ymrn8g6y6ukgsg76dh6qdm8ksql42x97088fywq0xr4ye"

[neutron.accounts.noble_outbound_ica]
library_account = "neutron1zcy7rk6ktyq284q4wxfc9lj60wsgraecpjtdkakkacd8t7s7axrqwylvht"
remote_addr = "noble10jn6a0f3vtv57hy5n8phjxpkujmvn2frzehrsaltjqwmyzfw5c5qvx5vt8"

[neutron.libraries]
neutron_ibc_transfer = "neutron1tglek29xk4ldzvg243rwr7tej6txlpzsp4j73xwrpp243azat67qmh7ghk"
noble_inbound_transfer = "neutron138kt3kcazh3ukwh7lj8w72rcqzeh4yaxtv80rc886hhktdp8yflq66g3w7"
noble_cctp_transfer = "neutron14008vsfpdry7y7rzqheht8da78ucjr8gdw6ujwdaw0zhm33cmqpqjsy5j8"
astroport_lper = "neutron1ywlzhkqf9kqkflpga5zdxw77544w80fqqu4emx9xl63n5nmdn98q6a09zg"
astroport_lwer = "neutron1flx08mnx49efrp7trayqwmlvykj6ll8y4j4wrgu8kw5kzjadx56sfnwxg4"
liquidation_forwarder = "neutron12j8wj0h4l3rlr80ndaaknwrtzdt4uhzd0g68cpk4xhdefgt07gkqfv3vlk"
authorizations = "neutron186lzesn2fsdwhzurzr0wq3cgvg9yal5nlre3qxuy724vqeyhdgpqe2jtlz"
processor = "neutron1qzvtwd5sggh402rly2lzjxgmqxl9jamndd499sj5eu89qc72kjfscxhsh0"

[ethereum]
rpc_url = "http://localhost:8545"
mnemonic = "test test test test test test test test test test test junk"

[ethereum.denoms]
usdc_erc20 = "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9"

[ethereum.accounts]
deposit = "0x5FbDB2315678afecb367f032d93F642f64180aa3"
withdraw = "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512"

[ethereum.libraries]
valence_vault = "0x9A676e781A523b5d0C0e43731313A708CB607508"
cctp_forwarder = "0x610178dA211FEF7D417bC0e6FeD39F05609AD788"
lite_processor = "0xA51c1fc2f0D1a1b8494Ed1FE312d7C3a78Ed91C0"
