[noble_cfg]
grpc_url = "http://0.0.0.0"
grpc_port = "41919"
chain_id = "localnoble-1"
mnemonic = "decorate bright ozone fork gallery riot bus exhaust worth way bone indoor calm squirrel merry zero scheme cotton until shop any excess stage laundry"

[neutron_cfg]
grpc_url = "http://0.0.0.0"
grpc_port = "39343"
chain_id = "localneutron-1"
mnemonic = "decorate bright ozone fork gallery riot bus exhaust worth way bone indoor calm squirrel merry zero scheme cotton until shop any excess stage laundry"
target_pool = "neutron1dtddh523nyqrtephncw4w6jewvcrwmsj84h49ylk2wkwqd8pu4lqt4tayl"

[neutron_cfg.denoms]
lp_token = "factory/neutron1dtddh523nyqrtephncw4w6jewvcrwmsj84h49ylk2wkwqd8pu4lqt4tayl/astroport/share"
usdc = "ibc/65D0BEC6DAD96C7F5043D1E54E54B6BB5D5B3AEC3FF6CEBB75B9E059F3580EA3"
ntrn = "untrn"

[neutron_cfg.accounts]
deposit = "neutron1dzgzkctfxyweqkkefnx9qwzswm5jjjwr5vqtr60984h0c0k5pf5s295s2y"
position = "neutron1gkrf5f0tg0qk25khr5dcvg2fymnnd7mh7lrmm9cms7djv8wlle6qkw6s7g"
withdraw = "neutron1acucaeeyf2ye9ad2dfjunkjtcejs4nrwd05q2qjtp9g5axhh9f8sgqhkqk"
liquidation = "neutron1s0ka2elsl8x7uh62rm9tty2n0cwl7tnlvpt5av44n4zg47uu8xsscymxdm"

[neutron_cfg.accounts.noble_inbound_ica]
library_account = "neutron12m5tss3x560z2pf2dqm5syxatzsuttqf59ek4csktgl0c4uqxcls8wyeme"
remote_addr = "noble1u70cwukpry8v53xghahzjaf0d6tjkfq7k94fhpscejtg20pzv7wq30ceqv"

[neutron_cfg.accounts.noble_outbound_ica]
library_account = "neutron1j86as73lkgml8pgg50w80cdj0wka7htd8har6yg89qxx9ullnfes4w9v4m"
remote_addr = "noble1pw4ygz9tymjpwjskm3rvm4aw820733mm8x5j9f98zdcu0yl76e9qwp26qn"

[neutron_cfg.libraries]
neutron_ibc_transfer = "neutron1e8d4xvu2dqv5hkpz6wrkrlajs2vgltchvq4m7m5rga2652jv3lnsq9vpgs"
noble_inbound_transfer = "neutron12cp3n29mpawd7jgw4z8dg2kjymeppe80a9f3h0yh9wskn7fy89hqf9hlp4"
noble_cctp_transfer = "neutron10farrngarlzpywcm46kq0z3vz0vs5g5t8jw79c642007gr36frkst452rx"
astroport_lper = "neutron1zlss8zjxdy65vt9atkdp26qhgzx9sf5f5wsgk7zkkxkjelv3ysjsxg2wkl"
astroport_lwer = "neutron1zl7udz2x0wpkkr6562j56apmmgxwe0jl7h42ca2jv9gts22cjvvs9yg9dv"
liquidation_forwarder = "neutron1rtyw998vhd5nzznngq69d5g2tvedtn9fqdz6lk5p0htqezs72xssk5u4mr"
authorizations = "neutron1zp2r0v9s43xk9n5we5c9nlu46saheel4auggcfm94uwncyz7973qw2qjd0"
processor = "neutron1gj67cecr8ykwr4ek254tscryw0tj6fusx2u9g8wztkxyffskr59q3m24we"

[ethereum_cfg]
rpc_url = "http://localhost:8545"
mnemonic = "test test test test test test test test test test test junk"

[ethereum_cfg.denoms]
usdc_erc20 = "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9"

[ethereum_cfg.accounts]
deposit = "0x5FbDB2315678afecb367f032d93F642f64180aa3"
withdraw = "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512"

[ethereum_cfg.libraries]
valence_vault = "0x9A676e781A523b5d0C0e43731313A708CB607508"
cctp_forwarder = "0x610178dA211FEF7D417bC0e6FeD39F05609AD788"
lite_processor = "0xA51c1fc2f0D1a1b8494Ed1FE312d7C3a78Ed91C0"
