[package]
name        = "valence-liquid-staking-utils"
version     = { workspace = true }
edition     = { workspace = true }
authors     = { workspace = true }
description = "Helpers for liquid staking integrations"

[dependencies]
cosmwasm-std    = { workspace = true }
cosmwasm-schema = { workspace = true }
