[package]
name        = "valence-bridging-utils"
version     = { workspace = true }
edition     = { workspace = true }
authors     = ["Timewave Labs"]
description = "Helpers for bridging"

[dependencies]
cosmwasm-std                = { workspace = true }
cosmwasm-schema             = { workspace = true }
