[contracts]

[contracts.code_ids.neutron]
valence_authorization    = 7217
valence_processor        = 7218
valence_base_account     = 7219
valence_forwarder        = 7222
valence_splitter         = 6049
valence_reverse_splitter = 3

[contracts.code_ids.cosmos-hub]
valence_authorization    = 7217
valence_processor        = 7218
valence_base_account     = 7219
valence_forwarder        = 7222
valence_splitter         = 6049
valence_reverse_splitter = 3
