[package]
name       = "valence-strategist-utils"
edition    = { workspace = true }
license    = { workspace = true }
version    = { workspace = true }
repository = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-schema = { workspace = true }
cosmwasm-std    = { workspace = true }
serde           = { workspace = true }
serde_json      = { workspace = true }
tokio           = "1.43.0"
async-trait     = "0.1.77"
bip32 = { version = "0.5", features = ["bip39"] }
cosmrs = { version = "0.21.1", features = [
    "cosmwasm",
    "rpc",
    "grpc",
]}
cosmos-sdk-proto = { version = "0.26.1", features = [
    "grpc-transport",
    "grpc",
]}
tonic = { version = "0.12.3", features = ["transport"] }
valence-processor-utils = { workspace = true }
# alloy-sol-types             = "0.7.7"
# alloy-primitives            = "0.7.7"
hex = "0.4.3"
localic-utils = { workspace = true }
# alloy          = { version = "0.11.1", features = ["full"] }
valence-e2e = { workspace = true }

alloy                                = { version = "0.9.2", features = ["full"] }
alloy_primitives_encoder             = { package = "alloy-primitives", version = "0.7.7" }
alloy_sol_types_encoder              = { package = "alloy-sol-types", version = "0.7.7" }
