[package]
name = "account-factory-demo"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[[bin]]
name = "account_factory_demo"
path = "src/main.rs"

[dependencies] 