# This is bridges config
#
# [bridges.[MAIN_CHAIN_NAME].[BRIDGE_TO_CHAIN].[BRIDGE_TYPE]]
#
# MAIN_CHAIN_NAME = the name of the main chain to be parsed to the config in code.
# Each main chain will have its own bridge files if we need it in the future.
#
# BRIDGE_TO_CHAIN = the name of the chain to which the bridge is connected
#
# BRIDGE_TYPE = the type of the bridge
#
# Bridge types and what they must include can be found in the `Bridges` enum in bridges.rs file

[bridges.neutron.cosmos-hub.polytone]
voice_addr           = "cosmos1vq2z7zgj7v4yj7z2zgj7v4yj7z2zgj7z2zgj7v"
connection_id        = "connection-0"
main_chain_note_port = "wasm.neutron1vq2z7zgj7v4yj7z2zgj7v4yj7z2zgj7z2zgj7v"

[bridges.neutron.juno.polytone]
voice_addr           = "cosmos1vq2z7zgj7v4yj7z2zgj7v4yj7z2zgj7z2zgj7v"
connection_id        = "connection-0"
main_chain_note_port = "wasm.neutron1vq2z7zgj7v4yj7z2zgj7v4yj7z2zgj7z2zgj7v"