name: Run a local-ic example Valence Program

inputs:
  chain-config: # id of input
    description: "Chain config to use for the test"
    required: true
  test-name:
    description: "Name of the test to run"
    required: true

runs:
  using: "composite"
  steps:
    - name: Cache Build artefacts
      uses: Swatinem/rust-cache@v2.7.5
      with:
        cache-on-failure: true
        shared-key: ${{ github.event.pull_request.number || github.ref }}

    - name: Get cargo
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: optimized-contracts
        path: ./artifacts

    - name: Download Forge artifacts
      uses: actions/download-artifact@v4
      with:
        name: forge-artifacts
        path: ./solidity/out/

    - name: List downloaded files
      shell: bash
      run: ls -l ./artifacts

    - name: Download local-ic artifact
      uses: actions/download-artifact@v4
      with:
        name: local-ic
        path: /tmp

    - name: Make local-ic executable
      shell: bash
      run: chmod +x /tmp/local-ic

    - name: Start local-ic and wait for it to be ready
      shell: bash
      run: ./scripts/start-local-ic.sh ${{ inputs.chain-config }}

    - name: Run local-ic example
      shell: bash
      env:
        RUST_LOG: debug
      run: cargo run --package ${{ inputs.test-name }}

    - name: Cleanup
      shell: bash
      run: killall local-ic && exit 0
