[bridges.neutron.cosmos_hub.polytone]
voice_addr      = "neutron1vq2z7zgj7v4yj7z2zgj7v4yj7z2zgj7z2zgj7v"
note_addr       = "neutron1vq2z7zgj7v4yj7z2zgj7v4yj7z2zgj7z2zgj7v"
other_note_port = "wasm.cosmos1vq2z7zgj7v4yj7z2zgj7v4yj7z2zgj7z2zgj7v"
connection_id   = "connection-0"
channel_id      = "channel-0"
[bridges.cosmos_hub.neutron.polytone]
voice_addr      = "cosmos1vq2z7zgj7v4yj7z2zgj7v4yj7z2zgj7z2zgj7v"
note_addr       = "cosmos1vq2z7zgj7v4yj7z2zgj7v4yj7z2zgj7z2zgj7v"
other_note_port = "wasm.neutron1vq2z7zgj7v4yj7z2zgj7v4yj7z2zgj7z2zgj7v"
connection_id   = "connection-0"
channel_id      = "channel-0"
