[package]
name        = "valence-gmp-utils"
version     = { workspace = true }
edition     = { workspace = true }
authors     = ["Timewave Labs"]
description = "Helpers for general message passing"

[dependencies]
cosmwasm-std                = { workspace = true }
cosmwasm-schema             = { workspace = true }
