[package]
name       = "generate_local_ic_config"
edition    = { workspace = true }
license    = { workspace = true }
version    = { workspace = true }
repository = { workspace = true }

[dependencies]
localic-std             = { git = "https://github.com/strangelove-ventures/interchaintest", branch = "main" }
localic-utils           = { git = "https://github.com/timewave-computer/localic-utils", branch = "main" }
polytone-note           = { git = "https://github.com/DA0-DA0/polytone", rev = "f70440a" }
polytone-voice          = { git = "https://github.com/DA0-DA0/polytone", rev = "f70440a" }
sha2                    = { workspace = true }
hex                     = { workspace = true }
serde_json              = { workspace = true }
env_logger              = { workspace = true }
log                     = { workspace = true }
rand                    = "0.8.5"
cosmos-grpc-client      = "3.0.1"
valence-program-manager = { workspace = true }
tokio                   = { workspace = true }
toml                    = "0.8.19"
valence-e2e             = { workspace = true }
clap                    = { workspace = true }
