name: Free disk space
description: We've run into out-of-disk error when compiling Rust projects, so we free up some space this way.

runs:
  using: "composite"
  steps:
    - name: Free Disk Space
      uses: jlumbroso/free-disk-space@1.3.1
      with:
        # this might remove tools that are actually needed,
        # if set to "true" but frees about 6 GB
        tool-cache: false
        
        # all of these default to true, but feel free to set to
        # "false" if necessary for your workflow
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true
