[package]
name    = "valence-splitter-service"
authors    = { workspace = true }
edition    = { workspace = true }
license    = { workspace = true }
version    = { workspace = true }
repository = { workspace = true }

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# use library feature to disable all instantiate/execute/query exports
library = []

[dependencies]
cosmwasm-schema       = { workspace = true }
cosmwasm-std          = { workspace = true }
cw-ownable            = { workspace = true }
cw-storage-plus       = { workspace = true }
cw-utils              = { workspace = true }
getset                = { workspace = true }
itertools             = { workspace = true }
schemars              = { workspace = true }
serde                 = { workspace = true }
thiserror             = { workspace = true }
valence-macros        = { workspace = true }
valence-service-utils = { workspace = true }
valence-service-base  = { workspace = true }

[dev-dependencies]
cw-multi-test              = { workspace = true }
cw-ownable                 = { workspace = true }
cw20                       = { workspace = true }
cw20-base                  = { workspace = true }
sha2                       = { workspace = true }
valence-account-utils      = { workspace = true }
valence-service-utils      = { workspace = true, features = ["testing"] }
valence-test-dynamic-ratio = { workspace = true }
