[package]
name        = "valence-liquidstaking-utils"
version     = { workspace = true }
edition     = { workspace = true }
authors     = { workspace = true }
description = "Helpers for liquidstaking integrations"

[dependencies]
cosmwasm-std    = { workspace = true }
cosmwasm-schema = { workspace = true }